[build]

  # This command builds the site
  command = "yarn build"

  # This is the directory that will be deployed
  publish = "dist"

  # This is where our functions are located
  functions = "dist"
[[redirects]]
  from = "/"
  to = "/.netlify/functions/graphql"
  status = 200

  [redirects.headers]
   Access-Control-Allow-Origin = "*"
   Access-Control-Allow-Methods = "GET,OPTIONS,PATCH,DELETE,POST,PUT"
   Access-Control-Allow-Headers = "*"
   Access-Control-Allow-Credentials = "true"
